### ISSUE TITLE
there is no source code

### ISSUE THREAD

**Issue by mattdavis0351** [mattdavis0351/fidelity-demo#1]
## Problem

This repo is currently empty.  

## Solution(s)

We need some sort of Python source code or nothing works

@IshanaRaina What do you think???

**Comment by IshanaRaina** [comment]
I don't say this often but you're right!

How about 
`print('Hello World')`
?

**Comment by mattdavis0351** [comment]
@IshanaRaina LGTM, I'll open a PR and link here in a moment

**Comment by mattdavis0351** [comment]
@IshanaRaina you can find the pr here #2

**Comment by mattdavis0351** [comment]
address in #2
